### ISSUE TITLE
Wrong tag name in manifest file

### ISSUE THREAD

**Issue by moba1** [jetstack/google-cas-issuer#113]
# What happend
I tried to apply [v0.7.1 manifest](https://github.com/jetstack/google-cas-issuer/releases/download/v0.7.1/google-cas-issuer-v0.7.1.yaml).
I successfully applied that manifest.

But, I got following error from deployed Pod in that manifest.

```yaml
message: 'rpc error: code = NotFound desc = failed to pull and unpack image
  "quay.io/jetstack/cert-manager-google-cas-issuer:v0.7.1": failed to resolve
   reference "quay.io/jetstack/cert-manager-google-cas-issuer:v0.7.1": quay.io/jetstack/cert-manager-google-cas-issuer:v0.7.1:
    not found'
reason: ErrImagePull
```

When I looked for the cause of that error, I found that manifest specifies image as `quay.io/jetstack/cert-manager-google-cas-issuer:v0.7.1`.
On the other hand, the tag in the image repository is `quay.io/jetstack/cert-manager-google-cas-issuer:0.7.1`, and there is no `quay.io/jetstack/cert-manager-google-cas-issuer:v0.7.1`.

# What to expect
That corrections be made to use the correct image in the manifest.

use `quay.io/jetstack/cert-manager-google-cas-issuer:0.7.1` on behalf of `quay.io/jetstack/cert-manager-google-cas-issuer:v0.7.1`.

**Comment by obliadp** [comment]
The v0.7.1 manifest also says that it's managed by Helm, and that the chart and app versions are both "v0.6.2", and it has a useless `app.kubernetes.io/instance: release-name` label.

**Comment by inteon** [comment]
Solved in the latest alpha release: https://github.com/jetstack/google-cas-issuer/releases/tag/v0.8.0-alpha.1
Generally, installing google-cas-issuer from the Helm chart seems like a safer choice.
