### ISSUE TITLE
No v0.8.0 Helm chart

### ISSUE THREAD

**Issue by mgoodness** [jetstack/google-cas-issuer#127]
It seems the v0.8.0 container image was published, but not the accompanying Helm chart version. This is important because RBAC has changed and is missing from v0.7.1 of the Helm chart.

```
❯ helm repo add jetstack https://charts.jetstack.io --force-update
"jetstack" has been added to your repositories

❯ helm search repo cert-manager-google-cas-issuer
NAME                                   	CHART VERSION	APP VERSION	DESCRIPTION                                
jetstack/cert-manager-google-cas-issuer	v0.7.1       	v0.7.1     	A Helm chart for jetstack/google-cas-issuer
```

**Comment by inteon** [comment]
Sorry @mgoodness will get this fixed ASAP.

**Comment by inteon** [comment]
@mgoodness the Helm chart should be available now.

**Comment by mgoodness** [comment]
> @mgoodness the Helm chart should be available now.

Thank you!!
