### ISSUE TITLE
High memory usage in issuer pod - OOM Error

### ISSUE THREAD

**Issue by abassettRH** [jetstack/google-cas-issuer#129]
I have been experiencing a problem recently with the google-cas-issuer pod memory usage growing extremely high (until it reaches the limit and has an OOM error, meaning it enters a CrashLoopBackoff). There are 2 main issues I have been seeing. The first being the memory climbing and the second being the pod looking for certificate requests that no longer exist. I am adding them both here as I believe they are related to pod memory usage increasing.

I have seen other people having similar issue of pod memory usage being very high this in issue #65. However, when I tried their proposed solution of setting a revisionHistoryLimit to 1, the CSRs that have been removed are then infinitely produced in logs as seen in issue #28 (which is meant to have been fixed in v0.2.0). I am unsure whether this is driving up the pod memory utilisation. The code that is generating the errors for the CSRs that no longer exist can be found here I believe:

https://github.com/jetstack/google-cas-issuer/blob/5579189ea76333a92edcbbd33400023d46699d68/pkg/controller/certificaterequest/certificaterequest_controller.go#L64-L75

I have been testing with certificates that expire every hour and renew 30 minute before to see the pod behaviour. Each time the certs are signed the memory utilisation spikes (which is not a problem) but after this operation happens, the pod memory decreases to higher rate than it was before and the pod looks for the previous certificate request objects. This is signalling to me that there is some sort of caching of Certifcate Request objects happening? Could this be driving up the memory?

This is a snippet of the error logs:

```shell
E0123 16:19:26.756349       1 controller.go:326]  "msg"="Reconciler error" "error"="CertificateRequest.cert-manager.io \"certificate-tcm7h-3\" not found" "certificateRequest"={"name":"certificate-tcm7h-3","namespace":"cas-test"} "controller"="certificaterequest" "controllerGroup"="cert-manager.io" "controllerKind"="CertificateRequest" "name"="certificate-tcm7h-3" "namespace"="cas-test" "reconcileID"="fcd9761d-de68-4f1f-8de2-2a73a861beee"
E0123 16:19:26.765695       1 controller.go:326]  "msg"="Reconciler error" "error"="CertificateRequest.cert-manager.io \"certificate-jngw9-3\" not found" "certificateRequest"={"name":"certificate-jngw9-3","namespace":"cas-test"} "controller"="certificaterequest" "controllerGroup"="cert-manager.io" "controllerKind"="CertificateRequest" "name"="certificate-jngw9-3" "namespace"="cas-test" "reconcileID"="ccb2e6e7-3fd6-4a21-b649-dc1017ae9fea"
E0123 16:19:26.765790       1 controller.go:326]  "msg"="Reconciler error" "error"="CertificateRequest.cert-manager.io \"certificate-8j5jw-3\" not found" "certificateRequest"={"name":"certificate-8j5jw-3","namespace":"cas-test"} "controller"="certificaterequest" "controllerGroup"="cert-manager.io" "controllerKind"="CertificateRequest" "name"="certificate-8j5jw-3" "namespace"="cas-test" "reconcileID"="18ac50d4-e3c9-427d-a372-8c858c53abbd"
E0123 16:19:26.765835       1 controller.go:326]  "msg"="Reconciler error" "error"="CertificateRequest.cert-manager.io \"certificate-84254-3\" not found" "certificateRequest"={"name":"certificate-84254-3","namespace":"cas-test"} "controller"="certificaterequest" "controllerGroup"="cert-manager.io" "controllerKind"="CertificateRequest" "name"="certificate-84254-3" "namespace"="cas-test" "reconcileID"="24fc9d66-e934-47fe-a583-51be95d64801"
E0123 16:19:26.765869       1 controller.go:326]  "msg"="Reconciler error" "error"="CertificateRequest.cert-manager.io \"certificate-l9rg9-3\" not found" "certificateRequest"={"name":"certificate-l9rg9-3","namespace":"cas-test"} "controller"="certificaterequest" "controllerGroup"="cert-manager.io" "controllerKind"="CertificateRequest" "name"="certificate-l9rg9-3" "namespace"="cas-test" "reconcileID"="1b553b69-2355-408c-bacf-9238a85b3164"
E0123 16:24:35.839887       1 controller.go:326]  "msg"="Reconciler error" "error"="CertificateRequest.cert-manager.io \"certificate-z4tjc-3\" not found" "certificateRequest"={"name":"certificate-z4tjc-3","namespace":"cas-test"} "controller"="certificaterequest" "controllerGroup"="cert-manager.io" "controllerKind"="CertificateRequest" "name"="certificate-z4tjc-3" "namespace"="cas-test" "reconcileID"="65c55be3-f8e5-45c9-a3da-77c7baa3e23d"
E0123 16:24:37.801408       1 controller.go:326]  "msg"="Reconciler error" "error"="CertificateRequest.cert-manager.io \"certificate-hdrlg-3\" not found" "certificateRequest"={"name":"certificate-hdrlg-3","namespace":"cas-test"}
```

**Comment by inteon** [comment]
@abassettRH are you still seeing this issue on the latest verion? (https://github.com/jetstack/google-cas-issuer/releases/tag/v0.8.0)
