### ISSUE TITLE
Improve the installation process

### ISSUE THREAD

**Issue by james-w** [jetstack/google-cas-issuer#37]
Currently the documented installation process needs the git repo and several commands.

We should have a one-liner that someone can run to get a working install with the CRDs, RBAC and deployment.

The docs should be updated to that, and the existing instructions can be kept for developer docs if we want.

We don't have to create any issuers, that can still be a manual step.

**Comment by jakexks** [comment]
There is a 1 line install attached to releases: https://github.com/jetstack/google-cas-issuer/releases/tag/v0.3.0

This should be documented

/assign

**Comment by jakexks** [comment]
Documented in v0.5.0
