### ISSUE TITLE
TLS certificates cannot be ingested by istio-ingressgateway due to missing newline characters

### ISSUE THREAD

**Issue by whatabout-bob** [jetstack/google-cas-issuer#39]
Description:
During the testing of the integration of the issuer with Istio ingress gateway secrets, we've found that the certificates cannot be ingested by the istio-proxy container in the ingress gateway pod due to a missing newline after each certificate. 

What's expected:
Newly-generated certificate secrets should be successfully ingested by istio-proxy upon creation or update (certificate rotation)

What's happening: 
Certificates are being rejected by istio-proxy with the following error: 
`[Envoy (Epoch 0)] [2021-06-10 18:24:34.984][21][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.auth.Secret rejected: Failed to load certificate chain from <inline>`

Versions affected: 
google-cas-issuer: 0.3.0
cert-manager: 1.1.0

How to reproduce: 
Generate a new certificate with google-cas-issuer in the istio-system namespace. The ingress-sds secret discovery container detects the secret and passes it to istio-proxy, where it is rejected with the error above. 

In testing the issue, I've found that we are running into the issue described here: [https://github.com/istio/istio/issues/22530](https://github.com/istio/istio/issues/22530). 

In order to validate, I was able to modify the generated secret and add a newline after _each_ certificate in the chain for ca.crt, tls.crt, and tls.key.  After adding these newline characters, the istio-proxy container successfully ingested the secret.

**Comment by jakexks** [comment]
Should be an easy enough fix.
/assign
