### ISSUE TITLE
v1beta1 API support?

### ISSUE THREAD

**Issue by elliotcourant** [jetstack/google-cas-issuer#44]
I might be totally off with this but it looks like certificate pools are no longer going to be part of the certificate management service google is providing? Looking [here](https://cloud.google.com/certificate-authority-service/docs/concepts) there is no mention of it and it is no longer present at all in the `gcloud beta privateca` command. 

```bash
$ gcloud beta privateca pools list
ERROR: (gcloud.beta.privateca) Invalid choice: 'pools'.
Maybe you meant:
  gcloud beta privateca certificates list
  gcloud beta privateca certificates create
  gcloud beta privateca certificates describe
  gcloud beta privateca certificates export
  gcloud beta privateca certificates revoke
  gcloud beta privateca certificates update
  gcloud beta privateca roots list
  gcloud beta privateca locations list
  gcloud beta privateca reusable-configs list
  gcloud beta privateca subordinates list

To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS
```

It looks like the API in general is also changing in v1beta1 https://cloud.google.com/certificate-authority-service/docs/reference/rest/v1beta1/projects.locations.certificateAuthorities 

Would you accept a pull request to try to bring the google-cas-issuer up to date with this newer API? Or do you feel that the API is subject to such change before GA that it is not worth making such a large (breaking) change at this point?

**Comment by jakexks** [comment]
Hi @elliotcourant 

I believe it's the other way around, the beta documentation is the out of date one. The v1 privateca api has been soft-launched, and is available for use after a `gcloud components update`. This is what the current version of `google-cas-issuer` supports. 

```
$ gcloud privateca
ERROR: (gcloud.privateca) Command name argument expected.

Available groups for gcloud privateca:

      certificates            Manage certificates.
      locations               Manage locations.
      pools                   Manage CA pools.
      roots                   Manage root certificate authorities.
      subordinates            Manage subordinate certificate authorities.
      templates               Manage certificate templates.

For detailed information on this command and its flags, run:
  gcloud privateca --help
  
$ gcloud privateca pools list
NAME            LOCATION      TIER
dry-run-pool    europe-west1  ENTERPRISE
```

The documentation on Google's side should follow shortly when the service becomes generally available.

**Comment by elliotcourant** [comment]
My concern, and maybe I'm misleading myself; is that if I create certificates/pools or anything using the v1 API I cannot see them at all in the UI. But creating certificates through v1beta1 I'm able to see them in the Google Cloud Management Console.

**Comment by elliotcourant** [comment]
I think I am getting confused and turned around sorry.

**Comment by jakexks** [comment]
The UI should appear once the service is generally available - which should be soon!

**Comment by jakexks** [comment]
The UI for the v1 API should now show up in the Google Cloud console, and the beta API should no longer be used.
