### ISSUE TITLE
Without json credential in the cas issuer authentication failing

### ISSUE THREAD

**Issue by mukesh-mohanan-db** [jetstack/google-cas-issuer#46]
its been mentioned in the document that if workload identity is enabled credentials in the CAS issuer issue optional. However i tried the option but its failing with permission issue [assuming authenitcation failure as I am not parsing json key]

**casClient.CreateCertificate failed: rpc error: code = PermissionDenied desc = Permission 'privateca.certificates.create' denied on 'projects/656342222/locations/europe-west1/caPools/PKIpool**

I followed  the below execution , not sure whether im missing any procedure in the documentation

```
gcloud privateca pools add-iam-policy-binding PKIpool --role=roles/privateca.certificateRequester --member="serviceAccount:sa-google-cas-issuer@$(gcloud config get-value project | tr ':' '/').iam.gserviceaccount.com" --location=europe-west1


export PROJECT=$(gcloud config get-value project | tr ':' '/')

gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:$PROJECT.svc.id.goog[cert-manager/ksa-google-cas-issuer]" \
  sa-google-cas-issuer@${PROJECT:?PROJECT is not set}.iam.gserviceaccount.com

kubectl annotate serviceaccount \
  --namespace cert-manager \
  ksa-google-cas-issuer \
  iam.gke.io/gcp-service-account=sa-google-cas-issuer@${PROJECT:?PROJECT is not set}.iam.gserviceaccount.com \
  --overwrite=true
```

**Comment by jakexks** [comment]
Hi @mukesh-mohanan-db 

The snippets from the README assume your Google Cloud service account is called sa-google-cas-issuer@<yourprojectid>.iam.gserviceaccount.com and your kubernetes service account is called ksa-google-cas-issuer in the cert-manager namespace. If any of these are incorrect those snippets won't work.

It looks like you successfully enabled workload identity but your google service account doesn't have permission to use the privateca.certificates.create API call.

to troubleshoot: `gcloud iam service-accounts list` should get you a list of service accounts. You can then check the policy bindings with `gcloud projects get-iam-policy  <your project ID>`

**Comment by mukesh-mohanan-db** [comment]
I confirm the service account has the certificate requester permission in the pool and also listed binding  and annotation command execution is successful  . I verified the service account permission via console as well

```

Updated IAM policy for CA Pool [PKI-pool].
bindings:
- members:
  - serviceAccount:sa-google-cas-issuer@project.iam.gserviceaccount.com
  role: roles/privateca.certificateRequester
etag: BwXGdTOpe7I=

export PROJECT=$(gcloud config get-value project | tr ':' '/')

gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:$PROJECT.svc.id.goog[cert-manager/ksa-google-cas-issuer]" \
  sa-google-cas-issuer@project.iam.gserviceaccount.com

kubectl annotate serviceaccount \
  --namespace cert-manager \
  ksa-google-cas-issuer \
  iam.gke.io/gcp-service-account=sa-google-cas-issuer@project.iam.gserviceaccount.com \
  --overwrite=true
```

**Comment by jakexks** [comment]
Where you write `project` have you redacted the name of your google cloud project?

Your original comment specified PKIpool where your latest comment specifies `PKI-pool`. I don't have enough information to help, please double-check your Issuer configuration 😅 .

**Comment by mukesh-mohanan-db** [comment]
its more or less occured with wrong service account usage closing the  same . thank you
