### ISSUE TITLE
google-cas-issuer pod gets OOM killed with default resource limits

### ISSUE THREAD

**Issue by rohansingh** [jetstack/google-cas-issuer#52]
I installed `google-cas-issuer` using the manifest available in releases:
https://github.com/jetstack/google-cas-issuer/releases/download/v0.5.3/google-cas-issuer-v0.5.3.yaml

It deployed successfully and the `google-cas-issuer` deployment was healthy. However, when I created a `Certificate`, the pod crashed with status `OOMKilled`.

It looks like the default memory limit specified in the manifest is `30Mi`. Increasing this to `90Mi` fixed the issue on my cluster.

**Comment by albertogeniola** [comment]
I can confirm this issue and that raising to 90Mi solves the problem.
I've created a [PR](https://github.com/jetstack/google-cas-issuer/pull/54) to fix this.

**Comment by albertogeniola** [comment]
@rohansingh 
I think this can be closed now.

**Comment by rohansingh** [comment]
Fixed in #54.
