### ISSUE TITLE
Using CAS certificate templates

### ISSUE THREAD

**Issue by xUnholy** [jetstack/google-cas-issuer#61]
I'm configuring the plugin to operate and use workload identity and provide the GSA IAM permissions to use a certificate template I created for TLS certificates specifically for GKE that I'd like cert-manager to use rather than providing certificateRequester against the CA/Pool.

Are there any existing documented examples or reasons why this wouldn't work? I'm currently getting the following issue:

```
2022-01-27T05:30:06.179Z	ERROR	controller-runtime.manager.controller.certificaterequest	Reconciler error	{"reconciler group": "cert-manager.io", "reconciler kind": "CertificateRequest", "name": "nginx-certificate-hb4mg", "namespace": "<REDACTED>", "error": "casClient.CreateCertificate failed: rpc error: code = PermissionDenied desc = Permission 'privateca.certificates.create' denied on 'projects/<REDACTED>/locations/<REDACTED>/caPools/<REDACTED>'"}
```

Any assistance here would be greatly appreciated!

**Comment by xUnholy** [comment]
If this isn't a feature I would have suspected that the CAS KSA has permissions to the template and/or there is a field `CertificateTemplate` which can be set on the Issuer https://github.com/jetstack/google-cas-issuer/blob/98f6d3e3d783e52df5ae1501cbb40c1104d8a2b3/api/v1beta1/googlecasissuer_types.go#L28

**Comment by sshcherbakov** [comment]
In the absence of partial string matching in the conditional IAM bindings for Google CAS, the use of templates remains important way of implementing domain ownership validation (for the cases when exact domain matching is not an option).

**Comment by sshcherbakov** [comment]
There is a relatively recent merged PR about CertificateTemplates:
https://github.com/jetstack/google-cas-issuer/commit/f4144e5ed2f83690561df23a7d5ab33924df8825
Wondering if they can now be specified.

**Comment by inteon** [comment]
This option was added in https://github.com/jetstack/google-cas-issuer/pull/100.
