### ISSUE TITLE
GKE updating K8S API to v1.22

### ISSUE THREAD

**Issue by albertogeniola** [jetstack/google-cas-issuer#62]
Hi all,

Google will force an update of K8S API to 1.22. This means that a number of v1beta resources won't be available any longer.
[Have a look at here](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes).

After a very quick research on this repo, I've seen there are various resources that must be upgraded in order to keep this workload functional:
- [ValidatingWebhookConfiguration (admissionregistration.k8s.io/v1beta1)](https://github.com/jetstack/google-cas-issuer/blob/4fae7887c28cef64b8781e637d1b3d7aae3a8ca3/config/default/webhookcainjection_patch.yaml)
- [MutatingWebhookConfiguration (admissionregistration.k8s.io/v1beta1)](https://github.com/jetstack/google-cas-issuer/blob/4fae7887c28cef64b8781e637d1b3d7aae3a8ca3/config/default/webhookcainjection_patch.yaml)
- [CustomResourceDefinition (apiextensions.k8s.io/v1beta1)](https://github.com/jetstack/google-cas-issuer/blob/4fae7887c28cef64b8781e637d1b3d7aae3a8ca3/config/crd/patches/cainjection_in_googlecasissuers.yaml)

Is there any plan to upgrade the current version of the component so that it'll support the v1.22 K8S API Level?

**Comment by JoshVanL** [comment]
Fixed in #73
