### ISSUE TITLE
Cannot find helm chart in jetstack charts repo

### ISSUE THREAD

**Issue by bkimbrough88** [jetstack/google-cas-issuer#83]
I am trying to install the chart, following the instructions in the readme, but I cannot find the chart where it says it should be. As you can see even after updating the repo, which `--force-update` should have done anyways, I cannot find a single issuer in the repo. Am I missing something here?

```
$ helm repo add jetstack https://charts.jetstack.io --force-update
"jetstack" has been added to your repositories

$ helm repo up
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...
Update Complete. ⎈Happy Helming!⎈

$ helm search repo issuer --devel
No results found
```

**Comment by fabx** [comment]
+1

**Comment by a-sallam-cw** [comment]
+1
Also is version 0.6.0 not released yet and still in alpha? the latest version we can see under releases is `0.5.3`

**Comment by mikejoseph-ah** [comment]
same here, has anyone fixed the issue?

**Comment by vijay0690** [comment]
+1 Same here. not able to use helm chat
`vijayprabahkar@vprabahkar-mbp ~ % helm pull jetstack/cert-manager-google-cas-issuer
Error: chart "cert-manager-google-cas-issuer" matching  not found in jetstack index. (try 'helm repo update'): no chart name found
vijayprabahkar@vprabahkar-mbp ~ %`

**Comment by mikejoseph-ah** [comment]
I gave up using this chart, seems not maintained, I am using now traefik + let's encrypt + cert-manager + (google)CloudDNS

**Comment by milesarmstrong** [comment]
+1 please can you release this chart via https://charts.jetstack.io

**Comment by julientard** [comment]
+1

**Comment by JoshVanL** [comment]
The helm chart should now be correctly available under `https://charts.jetstack.io`.

Please re-open this issue if this is not the case.

/close
