### ISSUE TITLE
Incorrect tag

### ISSUE THREAD

**Issue by xUnholy** [jetstack/google-cas-issuer#88]
https://github.com/jetstack/google-cas-issuer/blob/fcfd5485ccaf6f45710c32371dee41a547d9b359/deploy/charts/google-cas-issuer/values.yaml#L8

Should be `0.6.0` as shown here https://quay.io/repository/jetstack/cert-manager-google-cas-issuer?tab=tags&tag=latest

**Comment by D3vl0per** [comment]
Any update @SgtCoDFish ? Still not working on the 0.6.2 release!

**Comment by SgtCoDFish** [comment]
I'm actually gonna close this because it really looks like it's fixed. If you're having a specific problem please feel free to raise a GitHub issue!

(Caveat: There's currently limited bandwidth for maintaining this project so we might not be able to get back to you quickly)
